name: evently
services:
  postgres:
    image: 'postgres:14'
    environment:
      - TZ=Asia/Kolkata
      - PGTZ=Asia/Kolkata
      - 'POSTGRES_DB=evently_db'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'