spring:
  application:
    name: ${SPRING_APP_NAME:evently}

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:evently}?options=-c%20TimeZone%3DAsia/Kolkata
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:0}
    timeout: ${REDIS_TIMEOUT:2000}

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    table: ${FLYWAY_TABLE:flyway_schema_history}
    # Optional: set schema(s) if you don't use the default search_path
    # Accepts comma-separated list
    # schemas: ${FLYWAY_SCHEMAS:}